name: agenda_dr_zuniga
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  sembast: ^3.5.0+1
  sembast_web: ^2.0.0+1
  intl: ^0.18.1
  syncfusion_flutter_calendar: ^24.1.47
  provider: ^6.1.1
  flutter_slidable: ^3.0.1
  awesome_dialog: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/assets/images/imgLogo.png
    - assets/images/
    
  uses-material-design: true
